name: Docker

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches:
      - "**"
    tags:
      - 'v*.*.*'
    pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
        - "4.2.2-nvidia9.0"
        - "4.2.2-nvidia9.1"
        - "4.2.3-nvidia9.1"
        - "4.3.0-nvidia9.1"
        - "4.3.0-nvidia10.0"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Environment
      id: load-env
      run: |
        echo "DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

    - name: Setup Environment - Setup buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup Environment - Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.version }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/swaglive/ffmpeg:${{ matrix.version }}
        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.version=${{ matrix.version }}
          org.opencontainers.image.created=${{ env.DATE }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
